#!/usr/bin/env python
import os
import sys
from datetime import datetime
from dotenv import load_dotenv
from farcaster.HubService import HubService
from farcaster.fcproto.message_pb2 import MessageType, Message
import json
FARCASTER_EPOCH = 1609459200  # January 1, 2021 UTC

import base64
from protobuf_to_dict import protobuf_to_dict

import argparse

parser = argparse.ArgumentParser(prog="far2json", description="Convert fario export to json")
parser.add_argument("--lines", type=int, help="Only parse first <LINES>", default=0)
args = parser.parse_args()
"""

parser.add_argument("fid", type=int, help="FID")
parser.add_argument("--casts", help="User casts", action="store_true")
parser.add_argument("--links", help="User links", action="store_true")
parser.add_argument("--recasts", help="User recasts", action="store_true")
parser.add_argument("--likes", help="User likes", action="store_true")
parser.add_argument("--profile", help="User profile data", action="store_true")
parser.add_argument("--all", help="Equivalent to --casts --links --recasts --likes --profile", action="store_true")
parser.add_argument("--limit", type=int, help="Number of records. If more than one types of data are exported, the limit applies to each one separately.", default=sys.maxsize)
parser.add_argument("-a", "--address", help="Use the hub at <ADDRESS>. Ex. -a 192.168.1.1:2283", type=str)
parser.add_argument("-f", "--file", help="Write data to <FILE>. Default is stdout.", type=str)
parser.add_argument("-v", "--verbose", help="Verbose output", default=False, action="store_false")
args = parser.parse_args()
"""

print("[")
separator = ''
count=0
for line in sys.stdin:
	m = Message.FromString(base64.b64decode(line))
	out = json.dumps(protobuf_to_dict(m))
	print(separator+str(out))
	if not separator:
		separator = ', '
	if args.lines and count >= args.lines:
		break
		
print("]")